eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
    port: 8976


spring:
   data:
     mongodb:
#       uri : mongodb://dinesh:test@localhost:27017/admin
       uri: mongodb://admin:techorrs123@ds139689-a0.mlab.com:39689/rrs-dev-db
#       database  :  rrs-dev
       database  :  rrs-dev-db






