eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port:8978


spring:
#  cloud:
#    config:
#     uri: http://localhost:8888

   data:
     mongodb:
       uri : mongodb://dinesh:test@localhost:27017/admin
       database  :  rrs-dev






