eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
    port: 8976


spring:
   data:
     mongodb:
       uri : mongodb://diwwnesh:twwest@localhost:27017/awdmin
       database  :  rrss-dev






